### ISSUE TITLE
concatinate an int into the string

### ISSUE THREAD

**Issue by mohasarc** [mohasarc/WorkGround#1]
here order of type int is not being concatenated into the string
https://github.com/mohasarc/WorkGround/blob/85c0ac37550fd673b9a7c9e4fb7532441c94418c/workGround.cpp#L174

**Comment by mohasarc** [comment]
The problem was that the instream might still have some new line character that causes problems for getline fcn. solved by adding cin.ignore() before getline()

**Comment by YahyaMohamed26** [comment]
Close This
